In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import requests
from pprint import pprint

# We use the Alphavantage Api to get data for stock market

key = "J4YVHGYHLAUEEY9D"
symbol = "MSFT"  # For company names like MSFT = Microsoft, TSLA = Tesla, AAPL = Apple
url = "https://www.alphavantage.co/query"

params = {
    "function": "TIME_SERIES_DAILY",
    "symbol": symbol,
    "outputsize": "compact", 
    "datatype": "json",
    "apikey": key
}

response = requests.get(url, params=params)
if response.status_code == 200:
    data = response.json()
    # pprint(data)
else:
    print(f"Error {response.status_code}")

In [5]:
daily_data = data["Time Series (Daily)"]

In [6]:
df = pd.DataFrame.from_dict(daily_data, orient="index")
df.columns = ['open', 'high', 'low', 'close', 'volume']
df.index = pd.to_datetime(df.index)
df.head()

                open      high       low     close    volume
2026-03-24  382.3600  382.4700  371.8500  372.7400  42733625
2026-03-23  383.9000  387.2100  381.6800  383.0000  29680059
2026-03-20  386.7900  387.0000  380.1200  381.8700  50853154
2026-03-19  390.1000  392.4900  387.0600  389.0200  25138772
2026-03-18  397.1250  398.0000  391.0000  391.7900  25908484

In [7]:
lastSevenDays = df.tail(7)
lastSevenDays

                open      high       low     close    volume
2025-11-06  505.6600  505.7000  495.8100  497.1000  27406496
2025-11-05  513.3000  514.8300  506.5750  507.1600  22883851
2025-11-04  511.7600  515.5500  507.8400  514.3300  20958663
2025-11-03  519.8050  524.9600  514.5900  517.0300  22374742
2025-10-31  528.8750  529.3200  515.1000  517.8100  34006424
2025-10-30  530.4800  534.9700  522.1200  525.7600  41023088
2025-10-29  544.9400  546.2700  536.7287  541.5500  36023004